[package]
name = "pipe-channel"
version = "1.0.1"
authors = ["Sergey Bugaev <bugaevc@gmail.com>"]
license = "MIT"

description = "Channel implementation based on pipes"
keywords = ["pipe", "channel"]

documentation = "https://bugaevc.github.io/pipe-channel/pipe_channel/"
repository = "https://github.com/bugaevc/pipe-channel"

[dependencies]
nix = "0.6.0"
libc = "0.2.13"
